package render

import (
	"bytes"
	"encoding/json"
	"flag"
	"os"
	"path/filepath"
	"testing"

	"github.com/tristankenney/zdev/zdevd/internal/proto"
)

var updateRender = flag.Bool("update-render", false, "update render golden files from current code")

// refTimeUnix is the fixed reference time used in all TestVisualParity cases:
// 2026-05-04T12:00:00Z = 1777860000.
const refTimeUnix int64 = 1777860000

func nowFnFixed() int64 { return refTimeUnix }

// fixtureCases is the table of VIS + DATA fixture cases. pulseFrame and
// breathState pin the animator's state for deterministic byte output.
var fixtureCases = []struct {
	name        string
	prefix      string
	pulseFrame  int
	breathState int
}{
	{"VIS-01-markers", "vis-01", 0, 0},
	{"VIS-02-pulse-cycle", "vis-02", 4, 0},
	{"VIS-03-breath-bar", "vis-03", 0, 0},
	{"VIS-04-mood-glyph", "vis-04", 0, 0},
	{"VIS-05-hue-palette", "vis-05", 0, 0},
	{"VIS-06-footer-counts", "vis-06", 0, 0},
	{"VIS-07-two-row-layout", "vis-07", 0, 0},
	{"VIS-08-header", "vis-08", 0, 0},
	{"VIS-09-cursor-handling", "vis-09", 0, 0},
	{"VIS-10-differential-skip", "vis-10", 0, 0},
	{"VIS-11-truncation", "vis-11", 0, 0},
	{"VIS-12-stale-dim", "vis-12", 0, 0},
	{"VIS-13-current-session-bold", "vis-13", 0, 0},
	{"VIS-14-em-dash-placeholder", "vis-14", 0, 0},
	{"DATA-01-branch-chip", "data-01", 0, 0},
	{"DATA-02-dirty", "data-02", 0, 0},
	{"DATA-03-shell-cmd", "data-03", 0, 0},
	{"DATA-04-pr-aggregate", "data-04", 0, 0},
	{"DATA-05-pr-celebration", "data-05", 0, 0},
	{"DATA-06-ports", "data-06", 0, 0},
	{"DATA-07-activity-age", "data-07", 0, 0},
	{"DATA-08-agent-chips", "data-08", 0, 0},
	{"DATA-09-wait-age-escalation", "data-09", 0, 0},
	{"DATA-10-canonical-rows", "data-10", 0, 0},
}

// TestVisualParity exercises the Go renderer against 14 VIS + 10 DATA golden
// fixtures stored at testdata/golden/. The goldens were generated by THIS
// renderer at the time the fixtures were captured (Plan 03-07) — they are
// Go-self-referential, not captured from the bash baseline at
// ~/.local/bin/zdev-sidebar-render.
//
// Per the SC1 override recorded at
// .planning/phases/03-probes-renderer-parity/SC1-OVERRIDE.md (2026-05-05)
// and CONTEXT decision D3-08, this test verifies the Go renderer is
// internally consistent; bash parity deferred to Phase 4 drift detection.
//
// Phase 4's cutover step is responsible for the byte-for-byte comparison
// against captured bash renders. Until then, the implementation-time
// read-through against bash baseline lines (PATTERNS.md citations in
// chips.go and frame.go) is the implicit parity check; the bytes.Equal
// gate below is the explicit internal-consistency check.

// TestVisualParity is the byte-equality gate for all 24 VIS + DATA golden
// fixtures. For each fixture:
//  1. Read the *.snapshot.json to get the proto.Snapshot input.
//  2. Call Render with the pinned animator state and fixed nowFn.
//  3. bytes.Equal against the committed *.golden file.
//
// Run with -update-render to regenerate .golden files from current code.
func TestVisualParity(t *testing.T) {
	for _, tc := range fixtureCases {
		t.Run(tc.name, func(t *testing.T) {
			snapBytes, err := os.ReadFile(filepath.Join("testdata", "golden", tc.prefix+".snapshot.json"))
			if err != nil {
				t.Fatalf("read snapshot fixture: %v", err)
			}
			var snap proto.Snapshot
			if err := json.Unmarshal(snapBytes, &snap); err != nil {
				t.Fatalf("unmarshal snapshot: %v", err)
			}

			anim := NewAnimator()
			anim.OnSnapshot(&snap)
			// Pin animator state to the fixture's expected frame position.
			anim.pulseFrame = tc.pulseFrame
			anim.breathState = tc.breathState

			got := Render(&snap, 50, anim, nowFnFixed)
			goldenPath := filepath.Join("testdata", "golden", tc.prefix+".golden")

			if *updateRender {
				if err := os.MkdirAll(filepath.Dir(goldenPath), 0o755); err != nil {
					t.Fatalf("mkdir for golden: %v", err)
				}
				if err := os.WriteFile(goldenPath, got, 0o644); err != nil {
					t.Fatalf("write golden: %v", err)
				}
				t.Logf("updated %s (%d bytes)", goldenPath, len(got))
				return
			}

			want, err := os.ReadFile(goldenPath)
			if err != nil {
				t.Fatalf("read golden (run `go test -run TestVisualParity ./internal/render -update-render` to create): %v", err)
			}
			if !bytes.Equal(got, want) {
				t.Errorf("%s: bytes mismatch\nwant (%d bytes): %q\ngot  (%d bytes): %q",
					tc.name, len(want), want, len(got), got)
			}
		})
	}
}
